spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_V2jamxTob
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100

cors:
  allow-origin-patterns: ${CORS_ALLOW_ORIGINS_PATTERNS}

websocket:
  allow-origin-patterns: ${WEBSOCKET_ALLOW_ORIGINS} # comma separate list: http://localhost:63342, http://localhost:3000

naver-client-id: ${NAVER_CLIENT_ID}
naver-client-secret: ${NAVER_CLIENT_SECRET}

service-url: https://bside1512.dev
