= User API
:toc: left

== User-API

=== User 생성

operation::user-signup[snippets='http-request,http-response,request-fields']

== Activity

=== 전체 Activity 목록

operation::activity-list[snippets='http-request,response-fields,http-response']

=== 스피드게임 만들기

operation::speedgame-create[snippets='request-headers,http-request,request-fields,response-fields,http-response']

=== 스피드게임 방 조회

operation::speedgame-get-info[snippets='path-parameters,http-request,response-fields,http-response']

=== 기분체크인 만들기

operation::moodcheckin-create[snippets='request-headers,http-request,response-fields,http-response']

=== 기분체크인 방 조회

operation::moodcheckin-get-info[snippets='path-parameters,http-request,response-fields,http-response']

=== 감사 서클 만들기

operation::thankcircle-create[snippets='request-headers,http-request,response-fields,http-response']

=== 감사 서클 방 조회

operation::thankcircle-get-info[snippets='path-parameters,http-request,response-fields,http-response']

=== 미니 네트워킹 만들기

operation::mininetworking-create[snippets='request-headers,http-request,response-fields,http-response']

=== 미니 네트워킹 방 조회

operation::mininetworking-get-info[snippets='path-parameters,http-request,response-fields,http-response']

== 에러 케이스

=== 액티비티 방을 조회할 수 없는 경우 (모든 액티비티 동일)

operation::thankcircle-get-info-not-found[snippets='http-request,http-response']